name: Dumbflix Github Action CI

on: 
  push:
     branches: [ "master" ]
  pull_request:
     branches: [ "master" ]
  workflow_dispatch:
  
env:
  DOCKER_IMAGE_NAME: dumbflix-test

jobs:
  build:
    environment: "Github Action CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        echo "${REGISTRY_URL}"
        docker build --tg "${{ secrets.DOCKER_IMAGE_STAGING }}" .

    - name: Login to Registry
      run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin "${{ secrets.REGISTRY_URL }}"

    - name: Push to Registry
      run: docker push ${{ secrets.DOCKER_IMAGE_STAGING }}

    - name: Redeploy
      run: curl -fku "${{ secrets.RANCHER_TOKEN }}" -X POST -H "Accept:application/json" -H "Content-Type:application/json" "${{ secrets.RANCHER_URL }}"

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ✅ Build succeeded!
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.head_commit.message }}
          
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref }}
          Author: ${{ github.actor }}
          Repo: ${{ github.repository }}
          Workflow: ${{ github.workflow }}

  fail:
    environment: "Github Action CI"
    runs-on: ubuntu-latest
    needs: build
    if: needs.test-api.result == 'failure'
    steps:
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
         to: ${{ secrets.TELEGRAM_ID }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |
           ❌ Build failed!
           ${{ github.actor }} created commit:
           Commit message: ${{ github.event.head_commit.message }}
           
           Commit: ${{ github.sha }}
           Branch: ${{ github.ref }}
           Author: ${{ github.actor }}
           Repo: ${{ github.repository }}
           Workflow: ${{ github.workflow }}
