name: Dumbflix Github Action CI

on: 
  push:
     branches: [ "master" ]
  pull_request:
     branches: [ "master" ]
  workflow_dispatch:
  
env:
  DOCKER_IMAGE_NAME: dumbflix-test

jobs:
  build:
    environment: "Github Action CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        echo "${REGISTRY_URL}"
        docker build --tag "${{ secrets.DOCKER_IMAGE_STAGING }}" .

    - name: Login to Registry
      run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin "${{ secrets.REGISTRY_URL }}"

    - name: Push to Registry
      run: docker push ${{ secrets.DOCKER_IMAGE_STAGING }}

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: 103.150.197.209
        username: mentor
        key: ${{ secrets.KEY_SSH_LOLRANDOM }}
        port: 22
        script: docker-compose up -d
  

  success:
    environment: "Github Action CI"
    runs-on: ubuntu-latest
    needs: build
    if: always() && needs.build.result == 'success'
    steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ✅ Build succeeded!
          🧑 ${{ github.actor }} created commit:
          ✉ Commit message: ${{ github.event.head_commit.message }}
          
          Details :
          SHA: ${{ github.sha }}
          Workflow: ${{ github.workflow }}
          Repo: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Author: ${{ github.actor }}
                 

  fail:
    environment: "Github Action CI"
    runs-on: ubuntu-latest
    needs: build
    if: always() && needs.build.result == 'failure'
    steps:
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
         to: ${{ secrets.TELEGRAM_ID }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |
           ❌ Build not succeeded, lmao.
           🧑 ${{ github.actor }} created commit:
           ✉ Commit message: ${{ github.event.head_commit.message }}
          
           Details :
           SHA: ${{ github.sha }}
           Workflow: ${{ github.workflow }}
           Repo: ${{ github.repository }}
           Branch: ${{ github.ref }}
           Author: ${{ github.actor }}
